# export `lavaan' lav model description to third-party software
# 

lavExport <- function(object, target="lavaan", file=NULL) {

    target <- tolower(target)

    if(class(object) == "lavaan") {
        lav <- object@ParTable
    } else if(is.list(object)) {
        lav <- object
    } else {
        stop("lavaan ERROR: object must be of class `lavaan' or a parTable")
    }

    if(target == "lavaan") {
        model <- export_lavaan(lav)
    } else if(target == "mplus") {
        model <- export_Mplus(lav)
    } else if(target == "lisrel") {
        model <- export_lisrel(lav)
    } else if(target == "eqs") {
        model <- export_eqs(lav)
    } else if(target == "sem") {
        model <- export_sem(lav)
    } else if(target == "openmx") {
        model <- export_openmx(lav)
    } else {
        stop("lavaan ERROR: target", target, "has not been implemented yet")
    }
    
    if(!is.null(file)) {
        cat(model, file=file)
        return(invisible(model))
    } else {
        return(model)
    }
}

## FIXME: this is completely UNFINISHED (just  used to quickly get something)
export_lavaan <- function(lav) {

    header <- "# this model syntax is autogenerated by lavExport\n"
    footer <- "\n"
    lav2 <- ifelse(lav$free != 0L,
                   ifelse(lav$label == "",
                          paste(lav$lhs, lav$op, lav$rhs),
                          paste(lav$lhs, lav$op, lav$label, "*", lav$rhs)
                   ),
                   ifelse(lav$label == "",
                          paste(lav$lhs, lav$op, lav$ustart, "*", lav$rhs),
                          paste(lav$lhs, lav$op, lav$ustart, "*", lav$rhs, 
                                "+", lav$label, "*", lav$rhs)
                   )
            )

    body <- paste(lav2, collapse="\n")
    paste(header, body, footer, sep="")
}

export_mplus <- function(lav) {
    stop("this function needs revision")
}

export_lisrel <- function(lav) {
    stop("this function needs revision")
}

export.eqs <- function(lav) {
    stop("this function needs revision")
}

export.sem <- function(lav) {
    stop("this function needs revision")
}

export.openmx <- function(lav) {
    stop("this function needs revision")
}

