# export to Mplus syntax

lav_export_mplus <- function(lav, group_label = NULL) {
  lav <- lav_export_check(lav)
  header <- "  ! this model syntax is autogenerated by lav_export\n"
  footer <- "\n"

  lav <- as.data.frame(lav, stringsAsFactors = FALSE)
  ngroups <- lav_pt_ngroups(lav)

  lav_one_group <- function(lav) {
    # mplus does not like variable names with a 'dot'
    # replace them by an underscore '_'
    lav$lhs <- gsub("\\.", "_", lav$lhs)
    lav$rhs <- gsub("\\.", "_", lav$rhs)

    # remove contraints (:=, <, >, ==) here
    con_idx <- which(lav$op %in% c(":=", "<", ">", "=="))
    if (length(con_idx) > 0L) {
      lav <- lav[-con_idx, ]
    }

    # remove exogenous variances/covariances/intercepts...
    exo_idx <- which(lav$exo == 1L & lav$op %in% c("~~", "~1"))
    if (length(exo_idx)) {
      lav <- lav[-exo_idx, ]
    }

    # remove intercepts for categorical variables
    ord_names <- unique(lav$lhs[lav$op == "|"])
    ord_int_idx <- which(lav$op == "~1" & lav$lhs %in% ord_names)
    if (length(ord_int_idx)) {
      lav <- lav[-ord_int_idx, ]
    }

    # end of line
    lav$eol <- rep(";", length(lav$lhs))
    lav$ustart <- ifelse(is.na(lav$ustart), "", lav$ustart)
    lav$rhs2 <- ifelse(lav$free == 0L,
      paste("@", lav$ustart, sep = ""),
      paste("*", lav$ustart, sep = "")
    )
    lav$plabel <- gsub("\\.", "", lav$plabel)
    label <- ifelse(lav$label == "", lav$plabel, lav$label)
    lav$plabel <- ifelse(label == "", label,
      paste(" (", label, ")", sep = "")
    )

    # remove variances for ordered variables
    ov_names_ord <- lav_pt_vnames(lav, type = "ov.ord")
    ord_idx <- which(lav$lhs %in% ov_names_ord &
      lav$op == "~~" &
      lav$free == 0L &
      lav$lhs == lav$rhs)
    lav$lhs[ord_idx] <- paste("! ", lav$lhs[ord_idx], sep = "")
    lav$op[ord_idx] <- ""
    lav$rhs[ord_idx] <- ""

    # variances
    var_idx <- which(lav$op == "~~" & lav$rhs == lav$lhs)
    lav$op[var_idx] <- ""
    lav$rhs[var_idx] <- ""

    # scaling factors
    scal_idx <- which(lav$op == "~*~")
    lav$op[scal_idx] <- ""
    lav$rhs2[scal_idx] <- paste(lav$rhs2[scal_idx], "}", sep = "")
    lav$lhs[scal_idx] <- "{"

    # intercepts - excluding categorical observed
    int_idx <- which(lav$op == "~1")
    lav$op[int_idx] <- ""
    lav$rhs2[int_idx] <- paste(lav$rhs2[int_idx], "]", sep = "")
    lav$lhs[int_idx] <- paste("[", lav$lhs[int_idx], sep = "")

    # thresholds
    th_idx <- which(lav$op == "|")
    lav$op[th_idx] <- "$"
    lav$rhs[th_idx] <- gsub("t", "", x = lav$rhs[th_idx])
    lav$rhs2[th_idx] <- paste(lav$rhs2[th_idx], "]", sep = "")
    lav$lhs[th_idx] <- paste("[", lav$lhs[th_idx], sep = "")

    # replace binary operators
    lav$op <- ifelse(lav$op == "=~", " BY ", lav$op)
    lav$op <- ifelse(lav$op == "~", " ON ", lav$op)
    lav$op <- ifelse(lav$op == "~~", " WITH ", lav$op)


    lav2 <- paste(lav$lhs, lav$op, lav$rhs, lav$rhs2,
      lav$plabel, lav$eol,
      sep = ""
    )

    body <- paste(" ", lav2, collapse = "\n")

    body
  }

  if (ngroups == 1L) {
    body <- lav_one_group(lav)
  } else {
    group_values <- lav_pt_group_values(lav)
    # group 1
    body <- lav_one_group(lav[lav$group == group_values[1], ])

    if (is.null(group_label) || length(group_label) == 0L) {
      group_label <- paste(1:ngroups)
    }

    for (g in 2:ngroups) {
      body <- paste(body,
        paste("\nMODEL ", group_label[g], ":\n", sep = ""),
        lav_one_group(lav[lav$group == group_values[g], ]),
        sep = ""
      )
    }
  }

  # constraints go to a 'MODEL CONSTRAINTS' block
  con_idx <- which(lav$op %in% c(":=", "<", ">", "=="))
  if (length(con_idx) > 0L) {
    ### FIXME: we need to convert the operator
    ### eg b^2 --> b**2, others??
    lav$lhs[con_idx] <- gsub("\\^", "**", lav$lhs[con_idx])
    lav$rhs[con_idx] <- gsub("\\^", "**", lav$rhs[con_idx])

    constraints <- "\nMODEL CONSTRAINT:\n"
    # define 'new' variables
    def_idx <- which(lav$op == ":=")
    if (length(def_idx) > 0L) {
      def <- paste(lav$lhs[def_idx], collapse = " ")
      constraints <- paste(constraints, "NEW (", def, ");")
      lav$op[def_idx] <- "="
    }
    # replace '==' by '='
    eq_idx <- which(lav$op == "==")
    if (length(eq_idx) > 0L) {
      lav$op[eq_idx] <- "="
    }
    con <- paste(gsub("\\.", "", lav$lhs[con_idx]), " ",
      lav$op[con_idx], " ",
      gsub("\\.", "", lav$rhs[con_idx]), ";",
      sep = ""
    )
    con2 <- paste("  ", con, collapse = "\n")
    constraints <- paste(constraints, con2, sep = "\n")
  } else {
    constraints <- ""
  }

  out <- paste(header, body, constraints, footer, sep = "")
  class(out) <- c("lavaan.character", "character")
  out
}


# helper functions
lav_mplus_estimator <- function(object) {
  estimator <- object@Options$estimator
  if (estimator == "DWLS") {
    estimator <- "WLS"
  }

  # only 1 argument for 'test' is allowed
  if (length(object@Options$test) > 1L) {
    standard_idx <- which(object@Options$test == "standard")
    if (length(standard_idx) > 1L) {
      object@Options$test <- object@Options$test[-standard_idx]
    }
    if (length(object@Options$test) > 1L) {
      lav_msg_warn(gettext("only first (non-standard) test will be used"))
      object@Options$test <- object@Options$test[1]
    }
  }

  if (estimator == "ML") {
    if (object@Options$test %in% c("yuan.bentler", "yuan.bentler.mplus")) {
      estimator <- "MLR"
    } else if (object@Options$test == "satorra.bentler") {
      estimator <- "MLM"
    } else if (object@Options$test == "scaled.shifted") {
      estimator <- "MLMV"
    } else if (object@Options$se == "first.order") {
      estimator <- "MLF"
    }
  } else if (estimator %in% c("ULS", "WLS")) {
    if (object@Options$test == "satorra.bentler") {
      estimator <- paste(estimator, "M", sep = "")
    } else if (object@Options$test == "scaled.shifted") {
      estimator <- paste(estimator, "MV", sep = "")
    }
  } else if (estimator == "MML") {
    estimator <- "ML"
  }

  estimator
}

lav_mplus_header <- function(data_file = NULL, group_label = "", ov_names = "",
                             listwise = FALSE,
                             ov_ord_names = "", estimator = "ML",
                             meanstructure = FALSE,
                             weight_name = character(0L),
                             information = "observed",
                             data_type = "full", nobs = NULL) {
  # replace '.' by '_' in all variable names
  ov_names <- gsub("\\.", "_", ov_names)
  ov_ord_names <- gsub("\\.", "_", ov_ord_names)

  ### FIXME!!
  ### this is old code from lavaan 0.3-1
  ### surely, this can be done better...

  # TITLE command
  c_title <- "TITLE:\n"
  c_title <- paste(
    c_title,
    "  [This syntax is autogenerated by lav_export]\n"
  )

  # DATA command
  c_data <- "DATA:\n"
  ngroups <- length(data_file)
  if (ngroups == 1L) {
    c_data <- paste(c_data,
      "  file is ", data_file, ";\n",
      sep = ""
    )
  } else {
    for (g in 1:ngroups) {
      c_data <- paste(c_data,
        "  file (", group_label[g], ") is ",
        data_file[g], ";\n",
        sep = ""
      )
    }
  }
  if (data_type == "full") {
    c_data <- paste(c_data, "  type is individual;\n", sep = "")
    if (listwise) {
      c_data <- paste(c_data, "  listwise = on;\n", sep = "")
    }
  } else if (data_type == "moment") {
    c_data <- paste(c_data, "  type is fullcov;\n", sep = "")
    c_data <- paste(c_data, "  nobservations are ", nobs, ";\n", sep = "")
  } else {
    lav_msg_stop(gettext("data.type must be full or moment"))
  }

  # VARIABLE command
  c_variable <- "VARIABLE:\n"
  c_variable <- paste(c_variable, "  names are", sep = "")
  nvar <- length(ov_names)
  tmp <- 0
  for (i in 1:nvar) {
    if (tmp %% 6 == 0) {
      c_variable <- paste(c_variable, "\n    ", sep = "")
    }
    c_variable <- paste(c_variable, ov_names[i], sep = " ")
    tmp <- tmp + 1
  }
  c_variable <- paste(c_variable, ";\n", sep = "")
  # missing
  if (data_type == "full") {
    c_variable <- paste(c_variable,
      "  missing are all (-999999);\n",
      sep = ""
    )
  }
  # categorical?
  if (length(ov_ord_names)) {
    c_variable <- paste(c_variable, "  categorical are", sep = "")
    nvar <- length(ov_ord_names)
    tmp <- 0
    for (i in 1:nvar) {
      if (tmp %% 6 == 0) {
        c_variable <- paste(c_variable, "\n    ", sep = "")
      }
      c_variable <- paste(c_variable, ov_ord_names[i])
      tmp <- tmp + 1
    }
    c_variable <- paste(c_variable, ";\n", sep = "")
  }
  # weight variable?
  if (length(weight_name) > 0L) {
    c_variable <- paste(c_variable,
      "  weight = ", weight_name, ";\n",
      sep = ""
    )
  }

  # ANALYSIS command
  c_analysis <- paste("ANALYSIS:\n  type = general;\n", sep = "")
  c_analysis <- paste(c_analysis, "  estimator = ", toupper(estimator),
    ";\n",
    sep = ""
  )
  if (toupper(estimator) %in% c("ML", "MLR")) {
    c_analysis <- paste(c_analysis, "  information = ", information[1],
      ";\n",
      sep = ""
    )
  }
  if (!meanstructure) {
    c_analysis <- paste(c_analysis, "  model = nomeanstructure;\n",
      sep = ""
    )
  }

  # MODEL command
  c_model <- paste("MODEL:\n")

  # assemble pre-model header
  out <- paste(c_title, c_data, c_variable, c_analysis, c_model, sep = "")

  out
}
